export const GET_COVID_DATA = 'GET_COVID_DATA'
export const GET_COVID_DATA_REJECTED = 'GET_COVID_DATA_REJECTED'
export const GET_COVID_DATA_PENDING = 'GET_COVID_DATA_PENDING'
export const GET_COVID_DATA_FULFILLED = 'GET_COVID_DATA_FULFILLED'

export const GET_DAILY_COVID_DATA = 'GET_DAILY_COVID_DATA'
export const GET_DAILY_COVID_DATA_REJECTED = 'GET_DAILY_COVID_DATA_REJECTED'
export const GET_DAILY_COVID_DATA_PENDING = 'GET_DAILY_COVID_DATA_PENDING'
export const GET_DAILY_COVID_DATA_FULFILLED = 'GET_DAILY_COVID_DATA_FULFILLED'

export const GET_COUNTRY_COVID_DATA = 'GET_COUNTRY_COVID_DATA'
export const GET_COUNTRY_COVID_DATA_REJECTED = 'GET_COUNTRY_COVID_DATA_REJECTED'
export const GET_COUNTRY_COVID_DATA_PENDING = 'GET_COUNTRY_COVID_DATA_PENDING'
export const GET_COUNTRY_COVID_DATA_FULFILLED = 'GET_COUNTRY_COVID_DATA_FULFILLED'

export const CHANGE_COVID_COUNTRY = 'CHANGE_COVID_COUNTRY'
